name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
         with:
          global: true
          name: 'TENMAJKL'
          email: 'tenmajkl@liskyjidlokod.fun'
          actor: 'TENMAJKL'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: npm run deploy
